apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapi-deployment
  labels:
    app: demoapi
spec:
  replicas: 10
  selector:
    matchLabels:
      app: demoapi
  template:
    metadata:
      labels:
        app: demoapi
    spec:
      containers:
      - name: demoapi
        image: demoapi:v4
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /chaos
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: demoapi-service
spec:
  type: LoadBalancer
  selector:
    app: demoapi
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
