apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapi-deployment
  labels:
    app: demoapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapi
  template:
    metadata:
      labels:
        app: demoapi
    spec:
      containers:
      - name: demoapi
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demoapi-service
spec:
  type: LoadBalancer
  selector:
    app: demoapi
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
